spring:
  application:
    name: gateway
  cloud:
    consul:
      enabled: true
      discovery:
        # Get only services that are passing the health check
        query-passing: true
    gateway:
      routes:
        - id: multiplication-challenge-service
          uri: lb://multiplication-challenge-service/
          predicates:
            - Path=/challenges/**,/attempts,/attempts/**,/users/**
        - id: gamification
          uri: lb://gamification/
          predicates:
            - Path=/leaders
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - '*'
            allowedMethods:
              - GET
              - POST
              - OPTIONS
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST


server:
  port: 8000

logging:
  level:
    org.springframework.cloud.gateway.handler.predicate: trace